<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Authentication requests can contain any data, dependent on the IAuthenticator used
 */
class AuthenticationRequest extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'credentials',
            'isRequired' => true,
            'type' => TType::MAP,
            'ktype' => TType::STRING,
            'vtype' => TType::STRING,
            'key' => array(
                'type' => TType::STRING,
            ),
            'val' => array(
                'type' => TType::STRING,
                ),
        ),
    );

    /**
     * @var array
     */
    public $credentials = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'AuthenticationRequest';
    }


    public function read($input)
    {
        $tmp = $this->_read('AuthenticationRequest', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('AuthenticationRequest', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->credentials === null) {
            throw new TProtocolException('Required field AuthenticationRequest.credentials is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->credentials === null) {
            throw new TProtocolException('Required field AuthenticationRequest.credentials is unset!');
        }
    }
}
