<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Cassandra_execute_prepared_cql3_query_args extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'itemId',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'values',
            'isRequired' => true,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
        3 => array(
            'var' => 'consistency',
            'isRequired' => true,
            'type' => TType::I32,
        ),
    );

    /**
     * @var int
     */
    public $itemId = null;
    /**
     * @var string[]
     */
    public $values = null;
    /**
     * @var int
     */
    public $consistency = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'Cassandra_execute_prepared_cql3_query_args';
    }


    public function read($input)
    {
        $tmp = $this->_read('Cassandra_execute_prepared_cql3_query_args', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('Cassandra_execute_prepared_cql3_query_args', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->itemId === null) {
            throw new TProtocolException('Required field Cassandra_execute_prepared_cql3_query_args.itemId is unset!');
        }
        if ($this->values === null) {
            throw new TProtocolException('Required field Cassandra_execute_prepared_cql3_query_args.values is unset!');
        }
        if ($this->consistency === null) {
            throw new TProtocolException('Required field Cassandra_execute_prepared_cql3_query_args.consistency is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->itemId === null) {
            throw new TProtocolException('Required field Cassandra_execute_prepared_cql3_query_args.itemId is unset!');
        }
        if ($this->values === null) {
            throw new TProtocolException('Required field Cassandra_execute_prepared_cql3_query_args.values is unset!');
        }
        if ($this->consistency === null) {
            throw new TProtocolException('Required field Cassandra_execute_prepared_cql3_query_args.consistency is unset!');
        }
    }
}
