<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Cassandra_describe_splits_args extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'cfName',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'start_token',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'end_token',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'keys_per_split',
            'isRequired' => true,
            'type' => TType::I32,
        ),
    );

    /**
     * @var string
     */
    public $cfName = null;
    /**
     * @var string
     */
    public $start_token = null;
    /**
     * @var string
     */
    public $end_token = null;
    /**
     * @var int
     */
    public $keys_per_split = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'Cassandra_describe_splits_args';
    }


    public function read($input)
    {
        $tmp = $this->_read('Cassandra_describe_splits_args', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('Cassandra_describe_splits_args', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->cfName === null) {
            throw new TProtocolException('Required field Cassandra_describe_splits_args.cfName is unset!');
        }
        if ($this->start_token === null) {
            throw new TProtocolException('Required field Cassandra_describe_splits_args.start_token is unset!');
        }
        if ($this->end_token === null) {
            throw new TProtocolException('Required field Cassandra_describe_splits_args.end_token is unset!');
        }
        if ($this->keys_per_split === null) {
            throw new TProtocolException('Required field Cassandra_describe_splits_args.keys_per_split is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->cfName === null) {
            throw new TProtocolException('Required field Cassandra_describe_splits_args.cfName is unset!');
        }
        if ($this->start_token === null) {
            throw new TProtocolException('Required field Cassandra_describe_splits_args.start_token is unset!');
        }
        if ($this->end_token === null) {
            throw new TProtocolException('Required field Cassandra_describe_splits_args.end_token is unset!');
        }
        if ($this->keys_per_split === null) {
            throw new TProtocolException('Required field Cassandra_describe_splits_args.keys_per_split is unset!');
        }
    }
}
