<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class Cassandra_atomic_batch_mutate_args extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'mutation_map',
            'isRequired' => true,
            'type' => TType::MAP,
            'ktype' => TType::STRING,
            'vtype' => TType::MAP,
            'key' => array(
                'type' => TType::STRING,
            ),
            'val' => array(
                'type' => TType::MAP,
                'ktype' => TType::STRING,
                'vtype' => TType::LST,
                'key' => array(
                    'type' => TType::STRING,
                ),
                'val' => array(
                    'type' => TType::LST,
                    'etype' => TType::STRUCT,
                    'elem' => array(
                        'type' => TType::STRUCT,
                        'class' => '\cassandra\Mutation',
                        ),
                    ),
                ),
        ),
        2 => array(
            'var' => 'consistency_level',
            'isRequired' => true,
            'type' => TType::I32,
        ),
    );

    /**
     * @var array
     */
    public $mutation_map = null;
    /**
     * @var int
     */
    public $consistency_level =     1;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'Cassandra_atomic_batch_mutate_args';
    }


    public function read($input)
    {
        $tmp = $this->_read('Cassandra_atomic_batch_mutate_args', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('Cassandra_atomic_batch_mutate_args', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->mutation_map === null) {
            throw new TProtocolException('Required field Cassandra_atomic_batch_mutate_args.mutation_map is unset!');
        }
        if ($this->consistency_level === null) {
            throw new TProtocolException('Required field Cassandra_atomic_batch_mutate_args.consistency_level is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->mutation_map === null) {
            throw new TProtocolException('Required field Cassandra_atomic_batch_mutate_args.mutation_map is unset!');
        }
        if ($this->consistency_level === null) {
            throw new TProtocolException('Required field Cassandra_atomic_batch_mutate_args.consistency_level is unset!');
        }
    }
}
