<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Represents input splits used by hadoop ColumnFamilyRecordReaders
 */
class CfSplit extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'start_token',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'end_token',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'row_count',
            'isRequired' => true,
            'type' => TType::I64,
        ),
    );

    /**
     * @var string
     */
    public $start_token = null;
    /**
     * @var string
     */
    public $end_token = null;
    /**
     * @var int
     */
    public $row_count = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'CfSplit';
    }


    public function read($input)
    {
        $tmp = $this->_read('CfSplit', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('CfSplit', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->start_token === null) {
            throw new TProtocolException('Required field CfSplit.start_token is unset!');
        }
        if ($this->end_token === null) {
            throw new TProtocolException('Required field CfSplit.end_token is unset!');
        }
        if ($this->row_count === null) {
            throw new TProtocolException('Required field CfSplit.row_count is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->start_token === null) {
            throw new TProtocolException('Required field CfSplit.start_token is unset!');
        }
        if ($this->end_token === null) {
            throw new TProtocolException('Required field CfSplit.end_token is unset!');
        }
        if ($this->row_count === null) {
            throw new TProtocolException('Required field CfSplit.row_count is unset!');
        }
    }
}
