<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * ColumnParent is used when selecting groups of columns from the same ColumnFamily. In directory structure terms, imagine
 * ColumnParent as ColumnPath + '/../'.
 * 
 * See also <a href="cassandra.html#Struct_ColumnPath">ColumnPath</a>
 */
class ColumnParent extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        3 => array(
            'var' => 'column_family',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'super_column',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $column_family = null;
    /**
     * @var string
     */
    public $super_column = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'ColumnParent';
    }


    public function read($input)
    {
        $tmp = $this->_read('ColumnParent', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('ColumnParent', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->column_family === null) {
            throw new TProtocolException('Required field ColumnParent.column_family is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->column_family === null) {
            throw new TProtocolException('Required field ColumnParent.column_family is unset!');
        }
    }
}
