<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class CqlPreparedResult extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'itemId',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'count',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'variable_types',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
        4 => array(
            'var' => 'variable_names',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
    );

    /**
     * @var int
     */
    public $itemId = null;
    /**
     * @var int
     */
    public $count = null;
    /**
     * @var string[]
     */
    public $variable_types = null;
    /**
     * @var string[]
     */
    public $variable_names = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'CqlPreparedResult';
    }


    public function read($input)
    {
        $tmp = $this->_read('CqlPreparedResult', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('CqlPreparedResult', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->itemId === null) {
            throw new TProtocolException('Required field CqlPreparedResult.itemId is unset!');
        }
        if ($this->count === null) {
            throw new TProtocolException('Required field CqlPreparedResult.count is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->itemId === null) {
            throw new TProtocolException('Required field CqlPreparedResult.itemId is unset!');
        }
        if ($this->count === null) {
            throw new TProtocolException('Required field CqlPreparedResult.count is unset!');
        }
    }
}
