<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Row returned from a CQL query.
 * 
 * This struct is used for both CQL2 and CQL3 queries.  For CQL2, the partition key
 * is special-cased and is always returned.  For CQL3, it is not special cased;
 * it will be included in the columns list if it was included in the SELECT and
 * the key field is always null.
 */
class CqlRow extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'key',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'columns',
            'isRequired' => true,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\cassandra\Column',
                ),
        ),
    );

    /**
     * @var string
     */
    public $key = null;
    /**
     * @var \cassandra\Column[]
     */
    public $columns = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'CqlRow';
    }


    public function read($input)
    {
        $tmp = $this->_read('CqlRow', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('CqlRow', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->key === null) {
            throw new TProtocolException('Required field CqlRow.key is unset!');
        }
        if ($this->columns === null) {
            throw new TProtocolException('Required field CqlRow.columns is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->key === null) {
            throw new TProtocolException('Required field CqlRow.key is unset!');
        }
        if ($this->columns === null) {
            throw new TProtocolException('Required field CqlRow.columns is unset!');
        }
    }
}
