<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class CqlResult extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'type',
            'isRequired' => true,
            'type' => TType::I32,
            'class' => '\cassandra\CqlResultType',
        ),
        2 => array(
            'var' => 'rows',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\cassandra\CqlRow',
                ),
        ),
        3 => array(
            'var' => 'num',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        4 => array(
            'var' => 'schema',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\cassandra\CqlMetadata',
        ),
    );

    /**
     * @var int
     */
    public $type = null;
    /**
     * @var \cassandra\CqlRow[]
     */
    public $rows = null;
    /**
     * @var int
     */
    public $num = null;
    /**
     * @var \cassandra\CqlMetadata
     */
    public $schema = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'CqlResult';
    }


    public function read($input)
    {
        $tmp = $this->_read('CqlResult', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('CqlResult', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->type === null) {
            throw new TProtocolException('Required field CqlResult.type is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->type === null) {
            throw new TProtocolException('Required field CqlResult.type is unset!');
        }
    }
}
