<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class EndpointDetails extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'host',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'datacenter',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'rack',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $host = null;
    /**
     * @var string
     */
    public $datacenter = null;
    /**
     * @var string
     */
    public $rack = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'EndpointDetails';
    }


    public function read($input)
    {
        return $this->_read('EndpointDetails', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('EndpointDetails', self::$_TSPEC, $output);
    }


    private function _validateForWrite() {
        if ($this->host === null) {
            throw new TProtocolException('Required field EndpointDetails.host is unset!');
        }
        if ($this->datacenter === null) {
            throw new TProtocolException('Required field EndpointDetails.datacenter is unset!');
        }
    }
}
