<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class IndexOperator
{
    const EQ = 0;

    const GTE = 1;

    const GT = 2;

    const LTE = 3;

    const LT = 4;

    static public $__names = array(
        0 => 'EQ',
        1 => 'GTE',
        2 => 'GT',
        3 => 'LTE',
        4 => 'LT',
    );
}

