<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * The semantics of start keys and tokens are slightly different.
 * Keys are start-inclusive; tokens are start-exclusive.  Token
 * ranges may also wrap -- that is, the end token may be less
 * than the start one.  Thus, a range from keyX to keyX is a
 * one-element range, but a range from tokenY to tokenY is the
 * full ring.
 */
class KeyRange extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'start_key',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'end_key',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'start_token',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'end_token',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        6 => array(
            'var' => 'row_filter',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\cassandra\IndexExpression',
                ),
        ),
        5 => array(
            'var' => 'count',
            'isRequired' => true,
            'type' => TType::I32,
        ),
    );

    /**
     * @var string
     */
    public $start_key = null;
    /**
     * @var string
     */
    public $end_key = null;
    /**
     * @var string
     */
    public $start_token = null;
    /**
     * @var string
     */
    public $end_token = null;
    /**
     * @var \cassandra\IndexExpression[]
     */
    public $row_filter = null;
    /**
     * @var int
     */
    public $count = 100;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'KeyRange';
    }


    public function read($input)
    {
        $tmp = $this->_read('KeyRange', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('KeyRange', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->count === null) {
            throw new TProtocolException('Required field KeyRange.count is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->count === null) {
            throw new TProtocolException('Required field KeyRange.count is unset!');
        }
    }
}
