<?php
namespace cassandra;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class KsDef extends TBase
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'name',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'strategy_class',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'strategy_options',
            'isRequired' => false,
            'type' => TType::MAP,
            'ktype' => TType::STRING,
            'vtype' => TType::STRING,
            'key' => array(
                'type' => TType::STRING,
            ),
            'val' => array(
                'type' => TType::STRING,
                ),
        ),
        4 => array(
            'var' => 'replication_factor',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        5 => array(
            'var' => 'cf_defs',
            'isRequired' => true,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\cassandra\CfDef',
                ),
        ),
        6 => array(
            'var' => 'durable_writes',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
    );

    /**
     * @var string
     */
    public $name = null;
    /**
     * @var string
     */
    public $strategy_class = null;
    /**
     * @var array
     */
    public $strategy_options = null;
    /**
     * @deprecated ignored
     * 
     * @var int
     */
    public $replication_factor = null;
    /**
     * @var \cassandra\CfDef[]
     */
    public $cf_defs = null;
    /**
     * @var bool
     */
    public $durable_writes = true;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'KsDef';
    }


    public function read($input)
    {
        $tmp = $this->_read('KsDef', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('KsDef', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->name === null) {
            throw new TProtocolException('Required field KsDef.name is unset!');
        }
        if ($this->strategy_class === null) {
            throw new TProtocolException('Required field KsDef.strategy_class is unset!');
        }
        if ($this->cf_defs === null) {
            throw new TProtocolException('Required field KsDef.cf_defs is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->name === null) {
            throw new TProtocolException('Required field KsDef.name is unset!');
        }
        if ($this->strategy_class === null) {
            throw new TProtocolException('Required field KsDef.strategy_class is unset!');
        }
        if ($this->cf_defs === null) {
            throw new TProtocolException('Required field KsDef.cf_defs is unset!');
        }
    }
}
